# Generated by Django 3.1.7 on 2021-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default=None, upload_to='images')),
                ('review', models.BooleanField(default=False)),
            ],
        ),
    ]
