# Generated by Django 3.1.7 on 2021-06-08 06:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_coords_detection_detectionlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(default=None, max_length=18),
        ),
    ]
