# Generated by Django 3.1.7 on 2021-06-08 06:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_detectionlabel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(default='#C42B3B', max_length=18),
        ),
    ]
