# Generated by Django 3.1.7 on 2021-06-08 06:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_auto_20210608_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(default='#682874', max_length=18),
        ),
    ]
