# Generated by Django 3.1.7 on 2021-06-08 06:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_auto_20210608_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#100177', max_length=18, null=True),
        ),
    ]
