# Generated by Django 3.1.7 on 2021-06-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_auto_20210608_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlabel',
            name='color',
        ),
    ]
