# Generated by Django 3.1.7 on 2021-06-08 07:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_remove_detectionlabel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#656565', max_length=18, null=True),
        ),
    ]
