# Generated by Django 3.1.7 on 2021-06-08 07:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_auto_20210608_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlabel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
