# Generated by Django 3.1.7 on 2021-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_auto_20210608_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionimage',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
