# Generated by Django 3.1.7 on 2021-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20210418_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
